name: Generate 3D contribution graph

on:
  schedule:
    - cron: "30 0 * * *" # every day at 00:30 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.0
        with:
          username: PasindhuW
          # Themes available: dark, rose, night, night-green, night-rainbow, etc.
          # The action will create/update the ./profile-3d-contrib/*.svg files.

      - name: Commit 3D graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile-3d-contrib
          git commit -m "chore: update 3D contribution graph" || echo "No changes to commit"
          git push
